{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.aws.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.secretName }}
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  # These values should be provided during installation or via a separate process
  # The values below are placeholders and should be replaced with actual values
  access-key: {{ .Values.aws.accessKeyId | default "" | b64enc | quote }}
  secret-key: {{ .Values.aws.secretAccessKey | default "" | b64enc | quote }}
{{- end }}